
INSERT INTO polux.estado_solicitud VALUES (1, 'Radicada', 'La solicitud se encuentra radicada', 'RAD', true);
INSERT INTO polux.estado_solicitud VALUES (2, 'En Evaluación', 'La solicitud se encuentra en evaluación a cargo del ente responsable', 'EEV', true);
INSERT INTO polux.estado_solicitud VALUES (5, 'Rechazada', 'La solicitud fue evaluada y rechazada.', 'REC', true);
INSERT INTO polux.estado_solicitud VALUES (3, 'Aprobada', 'La solicitud fue evaluada y aprobada', 'APR', true);


INSERT INTO polux.tipo_solicitud VALUES (1, 'Solicitud de carta de presentación ante la empresa', 'Solicitud de carta de presentación ante la empresa que realiza el estudiante el proyecto', 'SCPAE', true);
INSERT INTO polux.tipo_solicitud VALUES (2, 'Solicitud inicial', 'Primera solicitud que realiza un estudiante para escoger una modalidad ', 'SI', true);
INSERT INTO polux.tipo_solicitud VALUES (3, 'Solicitud de cancelación de Modalidad de trabajo d', 'SOlicitud por la cual el estudiante cancela la modalidad de grado y el trabajo de grado ', 'SCM', true);
INSERT INTO polux.tipo_solicitud VALUES (4, 'Solicitud de cambio de director interno', 'Solicitud por medio de la cual se gestiona el cambio del director interno del trabajo de grado', 'SCDI', true);
INSERT INTO polux.tipo_solicitud VALUES (5, 'Solicitud de cambio de director externo', 'Solicitud por medio de la cual se realiza la  gestión para cambiar el director externo de un trabajo de grado.', 'SCDE', true);
INSERT INTO polux.tipo_solicitud VALUES (6, 'Solicitud de socialización', 'Solicitud por medio de la cual el estudiante solicita espacio para realizar la socialización de su trabajo de grado', 'SSO', true);
INSERT INTO polux.tipo_solicitud VALUES (7, 'Solicitud de prórroga', 'Solicitud por la cual el estudiante pide una prórroga para socializar o terminaro su proyecto de grado', 'SPR', true);
INSERT INTO polux.tipo_solicitud VALUES (8, 'Solicitud de modificación de datos del Trabajo de ', 'Solicitud por medio del cual el estudiante pide que sean modificados datos de su trabajo de gado.', 'SMDTG', true);
INSERT INTO polux.tipo_solicitud VALUES (9, 'Solicitud de cambio de materia', 'Solicitud por medio de la cual un estudiante con modalidad de materias de posgrado o profundización solicita que se cambie alguna de las materias solicitadas', 'SCMA', true);
INSERT INTO polux.tipo_solicitud VALUES (11, 'Solicitud de distinción (meritorio, laureado) ', 'Solicitud por medio de la cual el estudiante pide que su trabajo de grado sea distinguido', 'SDTG', true);
INSERT INTO polux.tipo_solicitud VALUES (10, 'Solicitud de cambio de evaluador(es)', 'Solicitud por medio de la cual el estudiatne pide que el evaluador del trabajo de grado sea cambiado', 'SCE', true);


INSERT INTO polux.modalidad VALUES (1, 'Pasantia', 'Modalidad que realiza el estudiante en una entidad nacional o internacional, asumiento el cáracter de práctica o de introducción a su quehacer profesional', 'PAS', true);
INSERT INTO polux.modalidad VALUES (3, 'Espacios Académicos de Profundización', 'Modalidad que realiza un estudiante de nivel Tecnológico en los programas de pregrado que ofrece la universidad', 'EAPRO', true);
INSERT INTO polux.modalidad VALUES (2, 'Espacios Académicos de Posgrado', 'Modalidad que realiza un estudiante en los programas de posgrado que ofrece la universidad', 'EAPOS', true);
INSERT INTO polux.modalidad VALUES (4, 'Monografía', 'Modalidad en la cual se realiza un ejercicio de aproximación y solución a un problema de investigación o de innovación en un campo de conocimiento', 'MONO', true);
INSERT INTO polux.modalidad VALUES (5, 'Investigación-Innovación', 'Modalidad que implica la vinculación de un estudiante con una estructura de investigación reconocida por Colciencias con un mínimo de un año de creación ', 'INV', true);
INSERT INTO polux.modalidad VALUES (7, 'Creación o Interpretación', 'Modalidad que recoge elementos inherentes al campo del arte y afines que permiten la producción de uan obra artistica', 'CRE', true);
INSERT INTO polux.modalidad VALUES (8, 'Proyecto de Emprendimiento', 'Modalidad que proyecta la  constitución formal de una empresa u organización a través de la construcción de un modelo de negocios o de la estructuración de un plan de negocios', 'PEMP', true);
INSERT INTO polux.modalidad VALUES (9, 'Producción Académica', 'Modalidad en la que elestudiante presenta evidencia de una publicación o aceptación de un artículo cientifico en revista homologada por el sistema de indexación nacional publindex de Colciencias ', 'PACAD', true);


INSERT INTO polux.modalidad_tipo_solicitud VALUES (1, 1, 1);
INSERT INTO polux.modalidad_tipo_solicitud VALUES (9, 10, 1);
INSERT INTO polux.modalidad_tipo_solicitud VALUES (2, 2, 1);
INSERT INTO polux.modalidad_tipo_solicitud VALUES (3, 3, 1);
INSERT INTO polux.modalidad_tipo_solicitud VALUES (4, 4, 1);
INSERT INTO polux.modalidad_tipo_solicitud VALUES (5, 5, 1);
INSERT INTO polux.modalidad_tipo_solicitud VALUES (10, 6, 1);
INSERT INTO polux.modalidad_tipo_solicitud VALUES (11, 7, 1);
INSERT INTO polux.modalidad_tipo_solicitud VALUES (12, 8, 1);
INSERT INTO polux.modalidad_tipo_solicitud VALUES (14, 3, 2);
INSERT INTO polux.modalidad_tipo_solicitud VALUES (15, 9, 2);
INSERT INTO polux.modalidad_tipo_solicitud VALUES (18, 3, 3);
INSERT INTO polux.modalidad_tipo_solicitud VALUES (19, 9, 3);
INSERT INTO polux.modalidad_tipo_solicitud VALUES (13, 2, 2);
INSERT INTO polux.modalidad_tipo_solicitud VALUES (16, 2, 3);
INSERT INTO polux.modalidad_tipo_solicitud VALUES (20, 2, 4);
INSERT INTO polux.modalidad_tipo_solicitud VALUES (21, 3, 4);
INSERT INTO polux.modalidad_tipo_solicitud VALUES (22, 4, 4);
INSERT INTO polux.modalidad_tipo_solicitud VALUES (23, 6, 4);
INSERT INTO polux.modalidad_tipo_solicitud VALUES (24, 10, 4);
INSERT INTO polux.modalidad_tipo_solicitud VALUES (25, 7, 4);
INSERT INTO polux.modalidad_tipo_solicitud VALUES (26, 8, 4);
INSERT INTO polux.modalidad_tipo_solicitud VALUES (27, 11, 4);
INSERT INTO polux.modalidad_tipo_solicitud VALUES (28, 2, 5);
INSERT INTO polux.modalidad_tipo_solicitud VALUES (29, 3, 5);
INSERT INTO polux.modalidad_tipo_solicitud VALUES (30, 4, 5);
INSERT INTO polux.modalidad_tipo_solicitud VALUES (31, 6, 5);
INSERT INTO polux.modalidad_tipo_solicitud VALUES (32, 10, 5);
INSERT INTO polux.modalidad_tipo_solicitud VALUES (33, 7, 5);
INSERT INTO polux.modalidad_tipo_solicitud VALUES (34, 8, 5);
INSERT INTO polux.modalidad_tipo_solicitud VALUES (35, 11, 5);
INSERT INTO polux.modalidad_tipo_solicitud VALUES (38, 2, 7);
INSERT INTO polux.modalidad_tipo_solicitud VALUES (39, 3, 7);
INSERT INTO polux.modalidad_tipo_solicitud VALUES (40, 4, 7);
INSERT INTO polux.modalidad_tipo_solicitud VALUES (41, 6, 7);
INSERT INTO polux.modalidad_tipo_solicitud VALUES (42, 10, 7);
INSERT INTO polux.modalidad_tipo_solicitud VALUES (43, 7, 7);
INSERT INTO polux.modalidad_tipo_solicitud VALUES (44, 8, 7);
INSERT INTO polux.modalidad_tipo_solicitud VALUES (45, 11, 7);
INSERT INTO polux.modalidad_tipo_solicitud VALUES (46, 2, 8);
INSERT INTO polux.modalidad_tipo_solicitud VALUES (47, 3, 8);
INSERT INTO polux.modalidad_tipo_solicitud VALUES (48, 4, 8);
INSERT INTO polux.modalidad_tipo_solicitud VALUES (49, 6, 8);
INSERT INTO polux.modalidad_tipo_solicitud VALUES (50, 10, 8);
INSERT INTO polux.modalidad_tipo_solicitud VALUES (51, 7, 8);
INSERT INTO polux.modalidad_tipo_solicitud VALUES (54, 8, 8);
INSERT INTO polux.modalidad_tipo_solicitud VALUES (55, 2, 9);
INSERT INTO polux.modalidad_tipo_solicitud VALUES (56, 3, 9);
INSERT INTO polux.modalidad_tipo_solicitud VALUES (57, 4, 9);
INSERT INTO polux.modalidad_tipo_solicitud VALUES (58, 6, 9);
INSERT INTO polux.modalidad_tipo_solicitud VALUES (59, 10, 9);
INSERT INTO polux.modalidad_tipo_solicitud VALUES (60, 7, 9);
INSERT INTO polux.modalidad_tipo_solicitud VALUES (61, 8, 9);
INSERT INTO polux.modalidad_tipo_solicitud VALUES (62, 11, 9);

INSERT INTO polux.tipo_detalle VALUES (1, 'Texto', NULL, 'txt', true);
INSERT INTO polux.tipo_detalle VALUES (2, 'Numerico', NULL, 'num', true);
INSERT INTO polux.tipo_detalle VALUES (3, 'Documento', NULL, 'doc', true);
INSERT INTO polux.tipo_detalle VALUES (4, 'Checkbox', NULL, 'check', true);
INSERT INTO polux.tipo_detalle VALUES (5, 'Lista Seleccionable', NULL, 'list', true);
INSERT INTO polux.tipo_detalle VALUES (6, 'Radio Button', NULL, 'rbtn', true);



INSERT INTO polux.detalle VALUES (1, 'Nombre Empresa', 'Ingrese el nombre de la empresa', 'Nombre de la empresa donde el estudiante va a realziar la pasantia', 'NEMP', true, 1);
INSERT INTO polux.detalle VALUES (2, 'Persona la que se dirige ', 'Ingrese el nombre de la persona a la cual va dirigida la carta', 'Nombre de la persona a la cual va dirigida la carta de presentacion ', 'PAL', true, 1);
INSERT INTO polux.detalle VALUES (3, 'Cargo de la persona a la que se dirige', 'Ingrese el cargo de la persona a la cual se dirige la carta', 'Cargo de la persona a la cual se dirige la carta', 'CPAL', true, 1);
INSERT INTO polux.detalle VALUES (4, 'Nombre propuesta', 'Ingrese el nombre de la propuesta', 'Nombre de  la propuesta del trabajo de grado', 'NPRO', true, 1);
INSERT INTO polux.detalle VALUES (6, 'Resumen propuesta', 'Escriba un resumen de su propuesta', 'Resumen de la propuesta de trabajo de grado', 'RPRO', true, 1);
INSERT INTO polux.detalle VALUES (7, 'Propuesta ', 'Cargue su propuesta', 'Documento que contiene la propuesta de trabajo de grado', 'PRO', true, 3);
INSERT INTO polux.detalle VALUES (8, 'Áreas de conocimiento', 'Seleccione las áreas de conocimiento que abarca su proyecto', 'Áreas de conocimiento que abarca el proyecto', 'ACON', true, 5);
INSERT INTO polux.detalle VALUES (9, 'Docente que avala la propuesta', 'Seleccione el docente que avala la propuesta', 'Codigo del docente que avala la propuesta', 'DAP', true, 5);
INSERT INTO polux.detalle VALUES (10, 'Certificación de afiliación ARL', 'Cargue la certificación de afiliación a la ARL', 'Certificación de afiliación a la ARL', 'CARL', true, 3);
INSERT INTO polux.detalle VALUES (12, 'Inscripción de los espacios académicos de trabajo ', 'Seleccione si desea solicitar la inscripción de los espacios académicos de trabajo de grado en el mismo periodo académico', 'Inscripción de los espacios académicos de trabajo de grado en el mismo periodo académico', 'IEAMP', true, 6);
INSERT INTO polux.detalle VALUES (13, 'Causa', 'Escriba la causa con la que justifica la solicitud', 'Causa con la cual se justifica alguna solicitud', 'CAUS', true, 1);
INSERT INTO polux.detalle VALUES (14, 'Director Anterior', 'Seleccione el nombre del director actual', 'Director actual del proyecto', 'DANT', true, 1);
INSERT INTO polux.detalle VALUES (16, 'Evaluador Anterior', 'Seleccione el nombre del anterior evaluador', 'Evaluador actual del proyecto', 'EVANT', true, 1);
INSERT INTO polux.detalle VALUES (15, 'Director Nuevo', 'Seleccione el docente que solicita como nuevo director', 'Director que se solicita ', 'DIRN', true, 5);
INSERT INTO polux.detalle VALUES (17, 'Evaluador Nuevo', 'Seleccione el nombre de la persona que solicita como nuevo evaluador', 'Evaluador que se solicita', 'EVNU', true, 5);
INSERT INTO polux.detalle VALUES (18, 'Hoja de vida del nuevo director externo', 'Cargue la hoja de vida del nnuevo director externo', 'Hoja de vida del nuevo director externo', 'HVDE', true, 3);
INSERT INTO polux.detalle VALUES (20, 'Tipo de prórroga', 'Seleccione el tipo de prórroga que va a solicitar', 'Tipo de prórroga que se va a solicitar (Para socializar o para finalizar)', 'TPRO', true, 5);
INSERT INTO polux.detalle VALUES (21, 'Programa Elegible', 'Seleccione el porgrama  que desea', 'Programa curricular que se va a solicitar', 'PELE', true, 5);
INSERT INTO polux.detalle VALUES (23, 'Espacio Academico Anterior', 'Seleccione el espacio academico que desea cancelar', 'Espacio academico que se va a cancelar', 'ESACAANT', true, 5);
INSERT INTO polux.detalle VALUES (22, 'Espacio Elegible', 'Seleccione los espacios academicos que desea solicitar', 'Espacios academicos que e van a solicitar', 'ESPELE', true, 4);
INSERT INTO polux.detalle VALUES (24, 'Espacio Academico Nuevo', 'Seleccione el espacio academico que solicita', 'Espacio academico qeu se solicita', 'ESACANUE', true, 5);
INSERT INTO polux.detalle VALUES (25, 'Nombre anterior de la propuesta ', 'Escriba el nombre de la propuesta anterior', 'Nombre anterior de la propuesta', 'NAP', true, 1);
INSERT INTO polux.detalle VALUES (26, 'Nombre nuevo de la propuesta', 'Escriba el nuevo nombre de la propuesta', 'Nuebo nombre de la propuesta', 'NNP', true, 1);
INSERT INTO polux.detalle VALUES (29, 'Nuevo resumen de propuesta', 'Escriba el nuevo resumen de su propuesta', 'Resumen nuevo de la propuesta', 'NRP', true, 1);
INSERT INTO polux.detalle VALUES (27, 'Anterior resumen de la propuesta', 'Escriba en anterior resumen de la propuesta', 'Resumen de la propuesta que sera cambiado', 'ARP', true, 1);
INSERT INTO polux.detalle VALUES (32, 'Nueva propuesta', 'Cargue la nueva propuesta', 'Nueva propuesta de trabajo de grado', 'NP', true, 3);
INSERT INTO polux.detalle VALUES (30, 'Anterior propuesta', 'Cargue la anterior propuesta ', 'Anterior propuesta de trabajo de grado', 'AP', true, 3);
INSERT INTO polux.detalle VALUES (33, 'Anteriores areas de conocimiento', 'Seleccione las anteriores areas de conocimiento', 'Anteriores areas de conocimiento', 'AAC', true, 5);
INSERT INTO polux.detalle VALUES (34, 'Nuevas áreas de conocimiento', 'Seleccione las nuevas áreas de conocimiento que abarca su proyecto', 'Nuevas áreas deconocimiento que abarca el proyecto', 'NAC', true, 5);
INSERT INTO polux.detalle VALUES (35, 'Plan de actividades de investigación', 'Cargue el Plan de actividades de investigación', 'Plan de actividades de investigación de la propuesta', 'PAI', true, 3);
INSERT INTO polux.detalle VALUES (36, 'Estructura de investigación que avala la propuesta', 'Seleccione  la Estructura de investigación que avala la propuesta', 'Estructura de investigación que avala la propuesta', 'EIAP', true, 5);
INSERT INTO polux.detalle VALUES (37, 'Docente director designado por la estructura de in', 'Seleccione l Docente director designado por la estructura de investigación', 'Docente director designado por la estructura de investigación', 'DDDI', true, 5);
INSERT INTO polux.detalle VALUES (38, 'Plan o modelo de negocios', 'Cargue el plan o el modelo de negocios', 'Plan  o modelo de negocios de la propuesta', 'POMN', true, 3);
INSERT INTO polux.detalle VALUES (39, 'Nombre del anterior director externo', 'Escriba el nombre del anterior director externo', 'Nombre del anterior director externo', 'NADE', true, 1);
INSERT INTO polux.detalle VALUES (40, 'Nombre del nuevo director externo', 'Escriba el nombre del nuevo director externo', 'Nombre del nuevo director externo', 'NNDE', true, 1);
INSERT INTO polux.detalle VALUES (41, 'Plan de actividades de investigación anterior', 'Cargue Plan de actividades de investigación anterior', 'Plan de actividades de investigación Anterior', 'PAIA', true, 3);
INSERT INTO polux.detalle VALUES (43, 'Plan de actividades de investigación nuevo', 'Cargue Plan de actividades de investigación nuevo', 'Plan de actividades de investigación nuevo', 'PAIN', true, 3);
INSERT INTO polux.detalle VALUES (44, 'Creacion individual o colectiva', 'Seleccione si su creación es individual o colectiva', 'Creación individual o colectiva', 'CIOC', true, 6);
INSERT INTO polux.detalle VALUES (46, 'Plan o modelo de negocios nuevo', 'Cargue el Plan o modelo de negocios nuevo', 'Plan o modelo de negocios nuevo', 'POMNN', true, 3);
INSERT INTO polux.detalle VALUES (45, 'Plan o modelo de negocios anterior', 'Cargue el Plan o modelo de negocios anterior', ' Plan o modelo de negocios anterior', 'POMNA', true, 3);



INSERT INTO polux.detalle_tipo_solicitud VALUES (1, 1, 1, true, true);
INSERT INTO polux.detalle_tipo_solicitud VALUES (2, 2, 1, true, true);
INSERT INTO polux.detalle_tipo_solicitud VALUES (3, 3, 1, true, true);
INSERT INTO polux.detalle_tipo_solicitud VALUES (4, 4, 2, true, true);
INSERT INTO polux.detalle_tipo_solicitud VALUES (5, 6, 2, true, true);
INSERT INTO polux.detalle_tipo_solicitud VALUES (6, 7, 2, true, true);
INSERT INTO polux.detalle_tipo_solicitud VALUES (7, 8, 2, true, true);
INSERT INTO polux.detalle_tipo_solicitud VALUES (8, 1, 2, true, true);
INSERT INTO polux.detalle_tipo_solicitud VALUES (9, 9, 2, true, true);
INSERT INTO polux.detalle_tipo_solicitud VALUES (10, 10, 2, true, true);
INSERT INTO polux.detalle_tipo_solicitud VALUES (11, 12, 2, true, true);
INSERT INTO polux.detalle_tipo_solicitud VALUES (12, 13, 3, true, true);
INSERT INTO polux.detalle_tipo_solicitud VALUES (13, 13, 4, true, true);
INSERT INTO polux.detalle_tipo_solicitud VALUES (14, 14, 4, true, true);
INSERT INTO polux.detalle_tipo_solicitud VALUES (15, 15, 4, true, true);
INSERT INTO polux.detalle_tipo_solicitud VALUES (16, 13, 9, true, true);
INSERT INTO polux.detalle_tipo_solicitud VALUES (17, 16, 9, true, true);
INSERT INTO polux.detalle_tipo_solicitud VALUES (18, 17, 9, true, true);
INSERT INTO polux.detalle_tipo_solicitud VALUES (19, 13, 5, true, true);
INSERT INTO polux.detalle_tipo_solicitud VALUES (21, 39, 5, true, true);
INSERT INTO polux.detalle_tipo_solicitud VALUES (22, 40, 5, true, true);
INSERT INTO polux.detalle_tipo_solicitud VALUES (23, 16, 5, true, true);
INSERT INTO polux.detalle_tipo_solicitud VALUES (24, 13, 11, true, true);
INSERT INTO polux.detalle_tipo_solicitud VALUES (25, 20, 11, true, true);
INSERT INTO polux.detalle_tipo_solicitud VALUES (26, 25, 12, true, true);
INSERT INTO polux.detalle_tipo_solicitud VALUES (27, 26, 12, true, true);
INSERT INTO polux.detalle_tipo_solicitud VALUES (28, 27, 12, true, true);
INSERT INTO polux.detalle_tipo_solicitud VALUES (29, 29, 12, true, true);
INSERT INTO polux.detalle_tipo_solicitud VALUES (30, 30, 12, true, true);
INSERT INTO polux.detalle_tipo_solicitud VALUES (31, 32, 12, true, true);
INSERT INTO polux.detalle_tipo_solicitud VALUES (32, 33, 12, true, true);
INSERT INTO polux.detalle_tipo_solicitud VALUES (33, 34, 12, true, true);
INSERT INTO polux.detalle_tipo_solicitud VALUES (34, 21, 13, true, true);
INSERT INTO polux.detalle_tipo_solicitud VALUES (37, 22, 13, true, true);
INSERT INTO polux.detalle_tipo_solicitud VALUES (38, 12, 13, true, true);
INSERT INTO polux.detalle_tipo_solicitud VALUES (39, 13, 14, true, true);
INSERT INTO polux.detalle_tipo_solicitud VALUES (40, 13, 15, true, true);
INSERT INTO polux.detalle_tipo_solicitud VALUES (41, 23, 15, true, true);
INSERT INTO polux.detalle_tipo_solicitud VALUES (42, 24, 15, true, true);
INSERT INTO polux.detalle_tipo_solicitud VALUES (43, 21, 16, true, true);
INSERT INTO polux.detalle_tipo_solicitud VALUES (44, 22, 16, true, true);
INSERT INTO polux.detalle_tipo_solicitud VALUES (45, 12, 16, true, true);
INSERT INTO polux.detalle_tipo_solicitud VALUES (46, 13, 18, true, true);
INSERT INTO polux.detalle_tipo_solicitud VALUES (47, 13, 19, true, true);
INSERT INTO polux.detalle_tipo_solicitud VALUES (49, 23, 19, true, true);
INSERT INTO polux.detalle_tipo_solicitud VALUES (50, 24, 19, true, true);
INSERT INTO polux.detalle_tipo_solicitud VALUES (51, 4, 20, true, true);
INSERT INTO polux.detalle_tipo_solicitud VALUES (52, 6, 20, true, true);
INSERT INTO polux.detalle_tipo_solicitud VALUES (53, 7, 20, true, true);
INSERT INTO polux.detalle_tipo_solicitud VALUES (54, 8, 20, true, true);
INSERT INTO polux.detalle_tipo_solicitud VALUES (55, 9, 20, true, true);
INSERT INTO polux.detalle_tipo_solicitud VALUES (56, 12, 20, true, true);
INSERT INTO polux.detalle_tipo_solicitud VALUES (57, 13, 21, true, true);
INSERT INTO polux.detalle_tipo_solicitud VALUES (58, 13, 22, true, true);
INSERT INTO polux.detalle_tipo_solicitud VALUES (59, 14, 22, true, true);
INSERT INTO polux.detalle_tipo_solicitud VALUES (60, 15, 22, true, true);
INSERT INTO polux.detalle_tipo_solicitud VALUES (61, 13, 24, true, true);
INSERT INTO polux.detalle_tipo_solicitud VALUES (62, 16, 24, true, true);
INSERT INTO polux.detalle_tipo_solicitud VALUES (63, 17, 24, true, true);
INSERT INTO polux.detalle_tipo_solicitud VALUES (64, 13, 25, true, true);
INSERT INTO polux.detalle_tipo_solicitud VALUES (65, 20, 25, true, true);
INSERT INTO polux.detalle_tipo_solicitud VALUES (66, 25, 26, true, true);
INSERT INTO polux.detalle_tipo_solicitud VALUES (67, 26, 26, true, true);
INSERT INTO polux.detalle_tipo_solicitud VALUES (68, 27, 26, true, true);
INSERT INTO polux.detalle_tipo_solicitud VALUES (69, 29, 26, true, true);
INSERT INTO polux.detalle_tipo_solicitud VALUES (70, 30, 26, true, true);
INSERT INTO polux.detalle_tipo_solicitud VALUES (71, 32, 26, true, true);
INSERT INTO polux.detalle_tipo_solicitud VALUES (72, 33, 26, true, true);
INSERT INTO polux.detalle_tipo_solicitud VALUES (73, 34, 26, true, true);
INSERT INTO polux.detalle_tipo_solicitud VALUES (74, 4, 28, true, true);
INSERT INTO polux.detalle_tipo_solicitud VALUES (75, 6, 28, true, true);
INSERT INTO polux.detalle_tipo_solicitud VALUES (76, 8, 28, true, true);
INSERT INTO polux.detalle_tipo_solicitud VALUES (77, 35, 28, true, true);
INSERT INTO polux.detalle_tipo_solicitud VALUES (78, 36, 28, true, true);
INSERT INTO polux.detalle_tipo_solicitud VALUES (79, 37, 28, true, true);
INSERT INTO polux.detalle_tipo_solicitud VALUES (80, 12, 28, true, true);
INSERT INTO polux.detalle_tipo_solicitud VALUES (81, 13, 29, true, true);
INSERT INTO polux.detalle_tipo_solicitud VALUES (82, 13, 30, true, true);
INSERT INTO polux.detalle_tipo_solicitud VALUES (83, 14, 30, true, true);
INSERT INTO polux.detalle_tipo_solicitud VALUES (84, 15, 30, true, true);
INSERT INTO polux.detalle_tipo_solicitud VALUES (85, 13, 32, true, true);
INSERT INTO polux.detalle_tipo_solicitud VALUES (86, 16, 32, true, true);
INSERT INTO polux.detalle_tipo_solicitud VALUES (87, 17, 32, true, true);
INSERT INTO polux.detalle_tipo_solicitud VALUES (88, 20, 33, true, true);
INSERT INTO polux.detalle_tipo_solicitud VALUES (89, 13, 33, true, true);
INSERT INTO polux.detalle_tipo_solicitud VALUES (90, 25, 34, true, true);
INSERT INTO polux.detalle_tipo_solicitud VALUES (91, 26, 34, true, true);
INSERT INTO polux.detalle_tipo_solicitud VALUES (92, 27, 34, true, true);
INSERT INTO polux.detalle_tipo_solicitud VALUES (93, 29, 34, true, true);
INSERT INTO polux.detalle_tipo_solicitud VALUES (94, 33, 34, true, true);
INSERT INTO polux.detalle_tipo_solicitud VALUES (95, 34, 34, true, true);
INSERT INTO polux.detalle_tipo_solicitud VALUES (96, 41, 34, true, true);
INSERT INTO polux.detalle_tipo_solicitud VALUES (97, 43, 34, true, true);
INSERT INTO polux.detalle_tipo_solicitud VALUES (98, 4, 38, true, true);
INSERT INTO polux.detalle_tipo_solicitud VALUES (100, 6, 38, true, true);
INSERT INTO polux.detalle_tipo_solicitud VALUES (101, 7, 38, true, true);
INSERT INTO polux.detalle_tipo_solicitud VALUES (102, 8, 38, true, true);
INSERT INTO polux.detalle_tipo_solicitud VALUES (103, 9, 38, true, true);
INSERT INTO polux.detalle_tipo_solicitud VALUES (104, 12, 38, true, true);
INSERT INTO polux.detalle_tipo_solicitud VALUES (105, 44, 38, true, true);
INSERT INTO polux.detalle_tipo_solicitud VALUES (106, 13, 39, true, true);
INSERT INTO polux.detalle_tipo_solicitud VALUES (107, 13, 40, true, true);
INSERT INTO polux.detalle_tipo_solicitud VALUES (108, 14, 40, true, true);
INSERT INTO polux.detalle_tipo_solicitud VALUES (109, 15, 40, true, true);
INSERT INTO polux.detalle_tipo_solicitud VALUES (112, 13, 42, true, true);
INSERT INTO polux.detalle_tipo_solicitud VALUES (114, 16, 42, true, true);
INSERT INTO polux.detalle_tipo_solicitud VALUES (115, 17, 42, true, true);
INSERT INTO polux.detalle_tipo_solicitud VALUES (116, 13, 43, true, true);
INSERT INTO polux.detalle_tipo_solicitud VALUES (117, 20, 43, true, true);
INSERT INTO polux.detalle_tipo_solicitud VALUES (118, 25, 44, true, true);
INSERT INTO polux.detalle_tipo_solicitud VALUES (119, 26, 44, true, true);
INSERT INTO polux.detalle_tipo_solicitud VALUES (120, 27, 44, true, true);
INSERT INTO polux.detalle_tipo_solicitud VALUES (121, 29, 44, true, true);
INSERT INTO polux.detalle_tipo_solicitud VALUES (122, 30, 44, true, true);
INSERT INTO polux.detalle_tipo_solicitud VALUES (123, 32, 44, true, true);
INSERT INTO polux.detalle_tipo_solicitud VALUES (124, 33, 44, true, true);
INSERT INTO polux.detalle_tipo_solicitud VALUES (125, 34, 44, true, true);
INSERT INTO polux.detalle_tipo_solicitud VALUES (126, 4, 46, true, true);
INSERT INTO polux.detalle_tipo_solicitud VALUES (127, 6, 46, true, true);
INSERT INTO polux.detalle_tipo_solicitud VALUES (128, 38, 46, true, true);
INSERT INTO polux.detalle_tipo_solicitud VALUES (129, 8, 46, true, true);
INSERT INTO polux.detalle_tipo_solicitud VALUES (130, 9, 46, true, true);
INSERT INTO polux.detalle_tipo_solicitud VALUES (131, 12, 46, true, true);
INSERT INTO polux.detalle_tipo_solicitud VALUES (132, 13, 47, true, true);
INSERT INTO polux.detalle_tipo_solicitud VALUES (133, 13, 48, true, true);
INSERT INTO polux.detalle_tipo_solicitud VALUES (134, 14, 48, true, true);
INSERT INTO polux.detalle_tipo_solicitud VALUES (135, 15, 48, true, true);
INSERT INTO polux.detalle_tipo_solicitud VALUES (136, 13, 50, true, true);
INSERT INTO polux.detalle_tipo_solicitud VALUES (137, 16, 50, true, true);
INSERT INTO polux.detalle_tipo_solicitud VALUES (138, 17, 50, true, true);
INSERT INTO polux.detalle_tipo_solicitud VALUES (139, 13, 51, true, true);
INSERT INTO polux.detalle_tipo_solicitud VALUES (140, 20, 51, true, true);
INSERT INTO polux.detalle_tipo_solicitud VALUES (141, 25, 54, true, true);
INSERT INTO polux.detalle_tipo_solicitud VALUES (142, 26, 54, true, true);
INSERT INTO polux.detalle_tipo_solicitud VALUES (143, 27, 54, true, true);
INSERT INTO polux.detalle_tipo_solicitud VALUES (144, 29, 54, true, true);
INSERT INTO polux.detalle_tipo_solicitud VALUES (146, 45, 54, true, true);
INSERT INTO polux.detalle_tipo_solicitud VALUES (147, 46, 54, true, true);
INSERT INTO polux.detalle_tipo_solicitud VALUES (148, 33, 54, true, true);
INSERT INTO polux.detalle_tipo_solicitud VALUES (149, 34, 54, true, true);
INSERT INTO polux.detalle_tipo_solicitud VALUES (151, 4, 55, true, true);
INSERT INTO polux.detalle_tipo_solicitud VALUES (152, 6, 55, true, true);
INSERT INTO polux.detalle_tipo_solicitud VALUES (153, 7, 55, true, true);
INSERT INTO polux.detalle_tipo_solicitud VALUES (154, 8, 55, true, true);
INSERT INTO polux.detalle_tipo_solicitud VALUES (155, 9, 55, true, true);
INSERT INTO polux.detalle_tipo_solicitud VALUES (156, 12, 55, true, true);
INSERT INTO polux.detalle_tipo_solicitud VALUES (157, 13, 56, true, true);
INSERT INTO polux.detalle_tipo_solicitud VALUES (158, 13, 57, true, true);
INSERT INTO polux.detalle_tipo_solicitud VALUES (159, 14, 57, true, true);
INSERT INTO polux.detalle_tipo_solicitud VALUES (160, 15, 57, true, true);
INSERT INTO polux.detalle_tipo_solicitud VALUES (161, 13, 59, true, true);
INSERT INTO polux.detalle_tipo_solicitud VALUES (162, 16, 59, true, true);
INSERT INTO polux.detalle_tipo_solicitud VALUES (163, 17, 59, true, true);
INSERT INTO polux.detalle_tipo_solicitud VALUES (164, 13, 60, true, true);
INSERT INTO polux.detalle_tipo_solicitud VALUES (165, 20, 60, true, true);
INSERT INTO polux.detalle_tipo_solicitud VALUES (166, 25, 61, true, true);
INSERT INTO polux.detalle_tipo_solicitud VALUES (167, 26, 61, true, true);
INSERT INTO polux.detalle_tipo_solicitud VALUES (168, 27, 61, true, true);
INSERT INTO polux.detalle_tipo_solicitud VALUES (169, 29, 61, true, true);
INSERT INTO polux.detalle_tipo_solicitud VALUES (170, 30, 61, true, true);
INSERT INTO polux.detalle_tipo_solicitud VALUES (171, 32, 61, true, true);
INSERT INTO polux.detalle_tipo_solicitud VALUES (172, 33, 61, true, true);
INSERT INTO polux.detalle_tipo_solicitud VALUES (173, 34, 61, true, true);




